# Generated by Django 5.1.2 on 2024-10-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaArteAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='nombre',
        ),
        migrations.AddField(
            model_name='artista',
            name='nombre_ape',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
